### ISSUE TITLE
Cannot set property 'mailer' of undefined     at new Ma

### ISSUE THREAD

**Issue by michielbdejong** [inrupt/solid-idp#23]
I just npm linked to the master branch and got:
```
(node:11471) UnhandledPromiseRejectionWarning: TypeError: Cannot set property 'mailer' of undefined
    at new Mail (/Users/michiel/gh/inrupt/solid-idp/node_modules/nodemailer/lib/mailer/index.js:45:33)
    at Object.module.exports.createTransport (/Users/michiel/gh/inrupt/solid-idp/node_modules/nodemailer/lib/nodemailer.js:58:14)
    at forgotPasswordInteractionHandler (/Users/michiel/gh/inrupt/solid-idp/dist/src/defaultConfiguration/handlers/forgotPasswordInteraction.handler.js:19:50)
    at handlers.forEach.handler (/Users/michiel/gh/inrupt/solid-idp/dist/src/defaultConfiguration/defaultConfiguration.js:95:34)
    at Array.forEach (<anonymous>)
    at Object.<anonymous> (/Users/michiel/gh/inrupt/solid-idp/dist/src/defaultConfiguration/defaultConfiguration.js:94:18)
    at Generator.next (<anonymous>)
    at fulfilled (/Users/michiel/gh/inrupt/solid-idp/dist/src/defaultConfiguration/defaultConfiguration.js:4:58)
    at process._tickCallback (internal/process/next_tick.js:68:7)
    at Function.Module.runMain (internal/modules/cjs/loader.js:757:11)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:622:3)
(node:11471) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:11471) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by michielbdejong** [comment]
Fixed in the dev branch

**Comment by Friat-Gaim** [comment]
can you get an answer for this error Dear if please help me

**Comment by jaxoncreed** [comment]
@Friat-Gaim What branch/version number are you operating on?
